# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd369c0a5d651e3b90577349a432ef59b138262e2ee033936e7dbe6598fc4015c47aa16de57918a370ee494755bc205b5171aeda78cb2f3a0bac17efb5d0a559

test:
  secret_key_base: f36d1db2dfdeb5bfc745fc405f26214ff9214891fff581448e18864aa97193272da2205ea14005f5209d78793d50047dcb9bd8b3c00b5fc6621650ff9dbeb3d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
